import Head from 'next/head'
import Layout from '../components/Layout/Layout';
import CollectionHeader from '../components/CollectionHeader/CollectionHeader';
import ProductList from '../components/ProductList/ProductList';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <CollectionHeader />
        <ProductList />
      </Layout>
    </div>
  );
}
